package com.example.client

import dev.icerock.moko.resources.StringResource
import dev.icerock.moko.resources.desc.StringDesc
import dev.icerock.moko.resources.desc.desc
import kotlin.js.ExperimentalJsExport
import kotlin.js.JsExport

@OptIn(ExperimentalJsExport::class)
@JsExport
class LocalText {
    fun getStringResource(resourceKey:String):StringResource {
        return when(resourceKey){
            "greeting"->MR.strings.greeting
            "login_too_short"->MR.strings.login_too_short
            "login_too_long"->MR.strings.login_too_long
            "login_already_exists"->MR.strings.login_already_exists
            "invalid_email"->MR.strings.invalid_email
            "email_already_exists"->MR.strings.email_already_exists
            "create_account"->MR.strings.create_account
            "sign_up_to_continue"->MR.strings.sign_up_to_continue
            "email_address"->MR.strings.email_address
            "login"->MR.strings.login
            "password"->MR.strings.password
            "re_enter_password"->MR.strings.re_enter_password
            "sign_up"->MR.strings.sign_up
            "or"->MR.strings.or
            "authorization_successful"->MR.strings.authorization_successful
            "authorization_failed"->MR.strings.authorization_failed
            "already_have_account"->MR.strings.already_have_an_account
            "sign_in"->MR.strings.sign_in
            "passwords_dont_match"->MR.strings.passwords_dont_match
            "invalid_password"->MR.strings.invalid_password
            "special_sign_in_later"->MR.strings.special_sign_in_later
            "too_many_email_requests"->MR.strings.too_many_email_requests
            "too_many_ip_requests"->MR.strings.too_many_ip_requests
            "too_many_user_requests"->MR.strings.too_many_user_requests
            "unexpected_error"->MR.strings.unexpected_error
            "something_wrong"->MR.strings.something_wrong
            "you_are_banned"->MR.strings.you_are_banned
            "invalid_date"->MR.strings.invalid_date
            "band_not_exist"->MR.strings.band_not_exist
            "invalid_year"->MR.strings.invalid_year
            "missing_album_add_data"->MR.strings.missing_album_add_data
            "album_exists_already"->MR.strings.album_exists_already
            "album_addition_received"->MR.strings.album_addition_received
            "missing_album_edit_data"->MR.strings.missing_album_edit_data
            "album_id_not_exist"->MR.strings.album_id_not_exist
            "album_title_exists"->MR.strings.album_title_exists
            "album_edition_received"->MR.strings.album_edition_received
            "album_deletion_received"->MR.strings.album_deletion_received
            "wrong_importance_studio"->MR.strings.wrong_importance_studio
            "wrong_importance_ep"->MR.strings.wrong_importance_ep
            "wrong_importance_other"->MR.strings.wrong_importance_other
            "wrong_release_date"->MR.strings.wrong_release_date
            "genre_not_exist"->MR.strings.genre_not_exist
            "url_too_long"->MR.strings.url_too_long
            "name_at_least_3"->MR.strings.name_at_least_3
            "name_at_least_2"->MR.strings.name_at_least_2
            "invalid_month_day"->MR.strings.invalid_month_day
            "missing_artist_add_data"->MR.strings.missing_artist_add_data
            "artist_addition_received"->MR.strings.artist_addition_received
            "missing_artist_edit_data"->MR.strings.missing_artist_edit_data
            "artist_not_exist"->MR.strings.artist_not_exist
            "artist_edition_received"->MR.strings.artist_edition_received
            "artist_deletion_received"->MR.strings.artist_deletion_received
            "artist_toggled"->MR.strings.artist_toggled
            "invalid_artist_birthdate"->MR.strings.invalid_artist_birthdate
            "artist_too_young"->MR.strings.artist_too_young
            "invalid_death_date"->MR.strings.invalid_death_date
            "invalid_gender"->MR.strings.invalid_gender
            "country_not_exist"->MR.strings.country_not_exist
            "start_end_not_null"->MR.strings.start_end_not_null
            "start_before_end"->MR.strings.start_before_end
            "invalid_start_year"->MR.strings.invalid_start_year
            "invalid_end_year"->MR.strings.invalid_end_year
            "invalid_status"->MR.strings.invalid_status
            "missing_band_add_data"->MR.strings.missing_band_add_data
            "band_addition_received"->MR.strings.band_addition_received
            "band_id_required"->MR.strings.band_id_required
            "missing_band_edit_data"->MR.strings.missing_band_edit_data
            "band_edition_received"->MR.strings.band_edition_received
            "band_deletion_received"->MR.strings.band_deletion_received
            "missing_member_add_data"->MR.strings.missing_member_add_data
            "member_exists"->MR.strings.member_exists
            "member_addition_received"->MR.strings.member_addition_received
            "member_id_required"->MR.strings.member_id_required
            "missing_member_edit_data"->MR.strings.missing_member_edit_data
            "member_not_exist"->MR.strings.member_not_exist
            "member_edition_received"->MR.strings.member_edition_received
            "member_deletion_received"->MR.strings.member_deletion_received
            "band_toggled"->MR.strings.band_toggled
            "formed_year_future"->MR.strings.formed_year_future
            "missing_formed"->MR.strings.missing_formed
            "formed_before_min"->MR.strings.formed_before_min
            "disbanded_before_min"->MR.strings.disbanded_before_min
            "disbanded_before_formed"->MR.strings.disbanded_before_formed
            "inconsistent_status"->MR.strings.inconsistent_status
            "missing_disbanded"->MR.strings.missing_disbanded
            "joined_future"->MR.strings.joined_future
            "left_future"->MR.strings.left_future
            "left_before_joined"->MR.strings.left_before_joined
            "artist_too_young_joining"->MR.strings.artist_too_young_joining
            "artist_dead_joining"->MR.strings.artist_dead_joining
            "artist_leave_when_dead"->MR.strings.artist_leave_when_dead
            "nickname_too_long"->MR.strings.nickname_too_long
            "role_too_long"->MR.strings.role_too_long
            "user_not_exist"->MR.strings.user_not_exist
            "table_not_exist"->MR.strings.table_not_exist
            "confirmation_success"->MR.strings.confirmation_success
            "addition_reverted"->MR.strings.addition_reverted
            "start_after_end"->MR.strings.start_after_end
            "event_addition_received"->MR.strings.event_addition_received
            "event_edition_received"->MR.strings.event_edition_received
            "event_delete_received"->MR.strings.event_delete_received
            "event_not_exist"->MR.strings.event_not_exist
            "event_id_required"->MR.strings.event_id_required
            "missing_event_add_data"->MR.strings.missing_event_add_data
            "event_name_too_long"->MR.strings.event_name_too_long
            "invalid_event_date"->MR.strings.invalid_event_date
            "genre_toggled"->MR.strings.genre_toggled
            "mod_not_exist"->MR.strings.mod_not_exist
            "cant_view"->MR.strings.cant_view
            "page_not_found"->MR.strings.page_not_found
            "user_banned"->MR.strings.user_banned
            "appeal_submitted"->MR.strings.appeal_submitted
            "ban_cancelled"->MR.strings.ban_cancelled
            "rank_too_low"->MR.strings.rank_too_low
            "no_report_reason"->MR.strings.no_report_reason
            "report_success"->MR.strings.report_success
            "resolved_success"->MR.strings.resolved_success
            "verification_code_sent"->MR.strings.verification_code_sent
            "bio_added"->MR.strings.bio_added
            "confirmed"->MR.strings.confirmed
            "birthday_added"->MR.strings.birthday_added
            "user_too_young"->MR.strings.user_too_young
            "account_not_found"->MR.strings.account_not_found
            "email_change"->MR.strings.email_change
            "new_email_exists"->MR.strings.new_email_exists
            "usernamed_changed"->MR.strings.usernamed_changed
            "usernamed_change_limit"->MR.strings.usernamed_change_limit
            "username_taken"->MR.strings.username_taken
            "logged_out"->MR.strings.logged_out
            "no_token"->MR.strings.no_token
            "account_created"->MR.strings.account_created
            "invalid_credentials"->MR.strings.invalid_credentials
            "password_changed"->MR.strings.password_changed
            "resend_code_in"->MR.strings.resend_code_in
            "resend_code"->MR.strings.resend_code
            "confirm_account"->MR.strings.confirm_account
            "done"->MR.strings.done
            "invalid_code"->MR.strings.invalid_code
            else->throw IllegalArgumentException("Unknown string resource: $resourceKey")
        }
    }

    fun getStringDesc(key:String):StringDesc{
        return getStringResource(key).desc()
    }
}
