package com.example.client

import dev.icerock.moko.resources.StringResource
import dev.icerock.moko.resources.desc.StringDesc
import dev.icerock.moko.resources.desc.desc
import kotlin.js.ExperimentalJsExport
import kotlin.js.JsExport

@OptIn(ExperimentalJsExport::class)
@JsExport
class LocalText {
    fun getStringResource(resourceKey:String):StringResource {
        return when(resourceKey){
            "greeting"->MR.strings.greeting
            "login_too_short"->MR.strings.login_too_short
            "login_too_long"->MR.strings.login_too_long
            "login_already_exists"->MR.strings.login_already_exists
            "invalid_email"->MR.strings.invalid_email
            "email_already_exists"->MR.strings.email_already_exists
            "create_account"->MR.strings.create_account
            "sign_up_to_continue"->MR.strings.sign_up_to_continue
            "email_address"->MR.strings.email_address
            "login"->MR.strings.login
            "password"->MR.strings.password
            "re_enter_password"->MR.strings.re_enter_password
            "sign_up"->MR.strings.sign_up
            "or"->MR.strings.or
            "authorization_successful"->MR.strings.authorization_successful
            "authorization_failed"->MR.strings.authorization_failed
            "already_have_account"->MR.strings.already_have_an_account
            "sign_in"->MR.strings.sign_in
            "passwords_dont_match"->MR.strings.passwords_dont_match
            "invalid_password"->MR.strings.invalid_password
            "special_sign_in_later"->MR.strings.special_sign_in_later
            "too_many_email_requests"->MR.strings.too_many_email_requests
            "too_many_ip_requests"->MR.strings.too_many_ip_requests
            "too_many_user_requests"->MR.strings.too_many_user_requests
            "unexpected_error"->MR.strings.unexpected_error
            "something_wrong"->MR.strings.something_wrong
            "you_are_banned"->MR.strings.you_are_banned
            "invalid_date"->MR.strings.invalid_date
            "band_not_exist"->MR.strings.band_not_exist
            "invalid_year"->MR.strings.invalid_year
            "missing_album_add_data"->MR.strings.missing_album_add_data
            "album_exists_already"->MR.strings.album_exists_already
            "album_addition_received"->MR.strings.album_addition_received
            "missing_album_edit_data"->MR.strings.missing_album_edit_data
            "album_id_not_exist"->MR.strings.album_id_not_exist
            "album_title_exists"->MR.strings.album_title_exists
            "album_edition_received"->MR.strings.album_edition_received
            "album_deletion_received"->MR.strings.album_deletion_received
            "wrong_importance_studio"->MR.strings.wrong_importance_studio
            "wrong_importance_ep"->MR.strings.wrong_importance_ep
            "wrong_importance_other"->MR.strings.wrong_importance_other
            "wrong_release_date"->MR.strings.wrong_release_date
            "genre_not_exist"->MR.strings.genre_not_exist
            "url_too_long"->MR.strings.url_too_long
            "name_at_least_3"->MR.strings.name_at_least_3
            "name_at_least_2"->MR.strings.name_at_least_2
            "invalid_month_day"->MR.strings.invalid_month_day
            "missing_artist_add_data"->MR.strings.missing_artist_add_data
            "artist_addition_received"->MR.strings.artist_addition_received
            "missing_artist_edit_data"->MR.strings.missing_artist_edit_data
            "artist_not_exist"->MR.strings.artist_not_exist
            "artist_edition_received"->MR.strings.artist_edition_received
            "artist_deletion_received"->MR.strings.artist_deletion_received
            "artist_toggled"->MR.strings.artist_toggled
            "invalid_artist_birthdate"->MR.strings.invalid_artist_birthdate
            "artist_too_young"->MR.strings.artist_too_young
            "invalid_death_date"->MR.strings.invalid_death_date
            "invalid_gender"->MR.strings.invalid_gender
            "country_not_exist"->MR.strings.country_not_exist
            "start_end_not_null"->MR.strings.start_end_not_null
            "start_before_end"->MR.strings.start_before_end
            "invalid_start_year"->MR.strings.invalid_start_year
            "invalid_end_year"->MR.strings.invalid_end_year
            "invalid_status"->MR.strings.invalid_status
            "missing_band_add_data"->MR.strings.missing_band_add_data
            "band_addition_received"->MR.strings.band_addition_received
            "band_id_required"->MR.strings.band_id_required
            "missing_band_edit_data"->MR.strings.missing_band_edit_data
            "band_edition_received"->MR.strings.band_edition_received
            "band_deletion_received"->MR.strings.band_deletion_received
            "missing_member_add_data"->MR.strings.missing_member_add_data
            "member_exists"->MR.strings.member_exists
            "member_addition_received"->MR.strings.member_addition_received
            "member_id_required"->MR.strings.member_id_required
            "missing_member_edit_data"->MR.strings.missing_member_edit_data
            "member_not_exist"->MR.strings.member_not_exist
            "member_edition_received"->MR.strings.member_edition_received
            "member_deletion_received"->MR.strings.member_deletion_received
            "band_toggled"->MR.strings.band_toggled
            "formed_year_future"->MR.strings.formed_year_future
            "missing_formed"->MR.strings.missing_formed
            "formed_before_min"->MR.strings.formed_before_min
            "disbanded_before_min"->MR.strings.disbanded_before_min
            "disbanded_before_formed"->MR.strings.disbanded_before_formed
            "inconsistent_status"->MR.strings.inconsistent_status
            "missing_disbanded"->MR.strings.missing_disbanded
            "joined_future"->MR.strings.joined_future
            "left_future"->MR.strings.left_future
            "left_before_joined"->MR.strings.left_before_joined
            "artist_too_young_joining"->MR.strings.artist_too_young_joining
            "artist_dead_joining"->MR.strings.artist_dead_joining
            "artist_leave_when_dead"->MR.strings.artist_leave_when_dead
            "nickname_too_long"->MR.strings.nickname_too_long
            "role_too_long"->MR.strings.role_too_long
            "user_not_exist"->MR.strings.user_not_exist
            "table_not_exist"->MR.strings.table_not_exist
            "confirmation_success"->MR.strings.confirmation_success
            "addition_reverted"->MR.strings.addition_reverted
            "start_after_end"->MR.strings.start_after_end
            "event_addition_received"->MR.strings.event_addition_received
            "event_edition_received"->MR.strings.event_edition_received
            "event_delete_received"->MR.strings.event_delete_received
            "event_not_exist"->MR.strings.event_not_exist
            "event_id_required"->MR.strings.event_id_required
            "missing_event_add_data"->MR.strings.missing_event_add_data
            "event_name_too_long"->MR.strings.event_name_too_long
            "invalid_event_date"->MR.strings.invalid_event_date
            "genre_toggled"->MR.strings.genre_toggled
            "mod_not_exist"->MR.strings.mod_not_exist
            "cant_view"->MR.strings.cant_view
            "page_not_found"->MR.strings.page_not_found
            "user_banned"->MR.strings.user_banned
            "appeal_submitted"->MR.strings.appeal_submitted
            "ban_cancelled"->MR.strings.ban_cancelled
            "rank_too_low"->MR.strings.rank_too_low
            "no_report_reason"->MR.strings.no_report_reason
            "report_success"->MR.strings.report_success
            "resolved_success"->MR.strings.resolved_success
            "verification_code_sent"->MR.strings.verification_code_sent
            "bio_added"->MR.strings.bio_added
            "confirmed"->MR.strings.confirmed
            "birthday_added"->MR.strings.birthday_added
            "user_too_young"->MR.strings.user_too_young
            "account_not_found"->MR.strings.account_not_found
            "email_change"->MR.strings.email_change
            "new_email_exists"->MR.strings.new_email_exists
            "usernamed_changed"->MR.strings.usernamed_changed
            "username_change_limit"->MR.strings.username_change_limit
            "username_taken"->MR.strings.username_taken
            "logged_out"->MR.strings.logged_out
            "no_token"->MR.strings.no_token
            "account_created"->MR.strings.account_created
            "invalid_credentials"->MR.strings.invalid_credentials
            "password_changed"->MR.strings.password_changed
            "resend_code_in"->MR.strings.resend_code_in
            "resend_code"->MR.strings.resend_code
            "confirm_account"->MR.strings.confirm_account
            "done"->MR.strings.done
            "invalid_code"->MR.strings.invalid_code
            "no_code"->MR.strings.no_code
            "login_email"->MR.strings.login_email
            "welcome"->MR.strings.welcome
            "sign_in_up"->MR.strings.sign_in_up
            "account_already"->MR.strings.account_already
            "continue_as"->MR.strings.continue_as
            "guest_question"->MR.strings.guest_question
            "back"->MR.strings.back
            "logout"->MR.strings.logout
            "not_found"->MR.strings.not_found
            "rate_limited"->MR.strings.rate_limited
            "invalid_otp"->MR.strings.invalid_otp
            "forbidden_login"->MR.strings.forbidden_login
            "reused_password"->MR.strings.reused_password
            "birthday_change_limit"->MR.strings.birthday_change_limit
            "forgot_password"->MR.strings.forgot_password
            "forgot_password_question"->MR.strings.forgot_password_question
            "password_link_sent"->MR.strings.password_link_sent
            "reset_password"->MR.strings.reset_password
            "create_new_password"->MR.strings.create_new_password
            "change_password"->MR.strings.change_password
            "rank1"->MR.strings.rank1
            "rank2"->MR.strings.rank2
            "rank3"->MR.strings.rank3
            "rank4"->MR.strings.rank4
            "rank5"->MR.strings.rank5
            "rank6"->MR.strings.rank6
            "rank7"->MR.strings.rank7
            "rank8"->MR.strings.rank8
            "rank9"->MR.strings.rank9
            "rank10"->MR.strings.rank10
            "rank11"->MR.strings.rank11
            "rank12"->MR.strings.rank12
            "rank13"->MR.strings.rank13
            "rank14"->MR.strings.rank14
            "rank15"->MR.strings.rank15
            "rank16"->MR.strings.rank16
            "rank17"->MR.strings.rank17
            "rank18"->MR.strings.rank18
            "united_states"->MR.strings.united_states
            "united_kingdom"->MR.strings.united_kingdom
            "germany"->MR.strings.germany
            "france"->MR.strings.france
            "spain"->MR.strings.spain
            "sweden"->MR.strings.sweden
            "norway"->MR.strings.norway
            "finland"->MR.strings.finland
            "poland"->MR.strings.poland
            "brazil"->MR.strings.brazil
            "italy"->MR.strings.italy
            "mexico"->MR.strings.mexico
            "denmark"->MR.strings.denmark
            "canada"->MR.strings.canada
            "belgium"->MR.strings.belgium
            "netherlands"->MR.strings.netherlands
            "afghanistan"->MR.strings.afghanistan
            "albania"->MR.strings.albania
            "algeria"->MR.strings.algeria
            "american_samoa"->MR.strings.american_samoa
            "andorra"->MR.strings.andorra
            "angola"->MR.strings.angola
            "anguilla"->MR.strings.anguilla
            "antigua_barbuda"->MR.strings.antigua_barbuda
            "argentina"->MR.strings.argentina
            "armenia"->MR.strings.armenia
            "aruba"->MR.strings.aruba
            "australia"->MR.strings.australia
            "austria"->MR.strings.austria
            "azerbaijan"->MR.strings.azerbaijan
            "bahamas_the"->MR.strings.bahamas_the
            "bahrain"->MR.strings.bahrain
            "bangladesh"->MR.strings.bangladesh
            "barbados"->MR.strings.barbados
            "belarus"->MR.strings.belarus
            "belize"->MR.strings.belize
            "benin"->MR.strings.benin
            "bermuda"->MR.strings.bermuda
            "bhutan"->MR.strings.bhutan
            "bolivia"->MR.strings.bolivia
            "bosnia_herzegovina"->MR.strings.bosnia_herzegovina
            "botswana"->MR.strings.botswana
            "british_virgin_is"->MR.strings.british_virgin_is
            "brunei"->MR.strings.brunei
            "bulgaria"->MR.strings.bulgaria
            "burkina_faso"->MR.strings.burkina_faso
            "burma"->MR.strings.burma
            "burundi"->MR.strings.burundi
            "cambodia"->MR.strings.cambodia
            "cameroon"->MR.strings.cameroon
            "cape_verde"->MR.strings.cape_verde
            "cayman_islands"->MR.strings.cayman_islands
            "central_african_rep"->MR.strings.central_african_rep
            "chad"->MR.strings.chad
            "chile"->MR.strings.chile
            "china"->MR.strings.china
            "colombia"->MR.strings.colombia
            "comoros"->MR.strings.comoros
            "congo_dem_rep"->MR.strings.congo_dem_rep
            "congo_repub_of_the"->MR.strings.congo_repub_of_the
            "cook_islands"->MR.strings.cook_islands
            "costa_rica"->MR.strings.costa_rica
            "cote_d_ivoire"->MR.strings.cote_d_ivoire
            "croatia_"->MR.strings.croatia_
            "cuba"->MR.strings.cuba
            "cyprus"->MR.strings.cyprus
            "czech_republic"->MR.strings.czech_republic
            "djibouti"->MR.strings.djibouti
            "dominica"->MR.strings.dominica
            "dominican_republic"->MR.strings.dominican_republic
            "east_timor"->MR.strings.east_timor
            "ecuador"->MR.strings.ecuador
            "egypt"->MR.strings.egypt
            "el_salvador"->MR.strings.el_salvador
            "equatorial_guinea"->MR.strings.equatorial_guinea
            "eritrea"->MR.strings.eritrea
            "estonia"->MR.strings.estonia
            "ethiopia"->MR.strings.ethiopia
            "faroe_islands"->MR.strings.faroe_islands
            "fiji"->MR.strings.fiji
            "french_guiana"->MR.strings.french_guiana
            "french_polynesia"->MR.strings.french_polynesia
            "gabon"->MR.strings.gabon
            "gambia"->MR.strings.gambia
            "georgia"->MR.strings.georgia
            "ghana"->MR.strings.ghana
            "gibraltar"->MR.strings.gibraltar
            "greece"->MR.strings.greece
            "greenland"->MR.strings.greenland
            "grenada"->MR.strings.grenada
            "guadeloupe"->MR.strings.guadeloupe
            "guam"->MR.strings.guam
            "guatemala"->MR.strings.guatemala
            "guernsey"->MR.strings.guernsey
            "guinea"->MR.strings.guinea
            "guinea_bissau"->MR.strings.guinea_bissau
            "guyana"->MR.strings.guyana
            "haiti"->MR.strings.haiti
            "honduras"->MR.strings.honduras
            "hong_kong"->MR.strings.hong_kong
            "hungary"->MR.strings.hungary
            "iceland"->MR.strings.iceland
            "india"->MR.strings.india
            "indonesia"->MR.strings.indonesia
            "iran"->MR.strings.iran
            "iraq"->MR.strings.iraq
            "ireland"->MR.strings.ireland
            "isle_of_man"->MR.strings.isle_of_man
            "israel"->MR.strings.israel
            "jamaica"->MR.strings.jamaica
            "japan"->MR.strings.japan
            "jersey"->MR.strings.jersey
            "jordan"->MR.strings.jordan
            "kazakhstan"->MR.strings.kazakhstan
            "kenya"->MR.strings.kenya
            "kiribati"->MR.strings.kiribati
            "korea_north"->MR.strings.korea_north
            "korea_south"->MR.strings.korea_south
            "kuwait"->MR.strings.kuwait
            "kyrgyzstan"->MR.strings.kyrgyzstan
            "laos"->MR.strings.laos
            "latvia"->MR.strings.latvia
            "lebanon"->MR.strings.lebanon
            "lesotho"->MR.strings.lesotho
            "liberia"->MR.strings.liberia
            "libya"->MR.strings.libya
            "liechtenstein"->MR.strings.liechtenstein
            "lithuania"->MR.strings.lithuania
            "luxembourg"->MR.strings.luxembourg
            "macau"->MR.strings.macau
            "macedonia"->MR.strings.macedonia
            "madagascar"->MR.strings.madagascar
            "malawi"->MR.strings.malawi
            "malaysia"->MR.strings.malaysia
            "maldives"->MR.strings.maldives
            "mali"->MR.strings.mali
            "malta"->MR.strings.malta
            "marshall_islands"->MR.strings.marshall_islands
            "martinique"->MR.strings.martinique
            "mauritania"->MR.strings.mauritania
            "mauritius"->MR.strings.mauritius
            "mayotte"->MR.strings.mayotte
            "micronesia"->MR.strings.micronesia
            "moldova"->MR.strings.moldova
            "monaco"->MR.strings.monaco
            "mongolia"->MR.strings.mongolia
            "montserrat"->MR.strings.montserrat
            "morocco"->MR.strings.morocco
            "mozambique"->MR.strings.mozambique
            "namibia"->MR.strings.namibia
            "nauru"->MR.strings.nauru
            "nepal"->MR.strings.nepal
            "netherlands_antilles"->MR.strings.netherlands_antilles
            "new_caledonia"->MR.strings.new_caledonia
            "new_zealand"->MR.strings.new_zealand
            "nicaragua"->MR.strings.nicaragua
            "niger"->MR.strings.niger
            "nigeria"->MR.strings.nigeria
            "n_mariana_islands"->MR.strings.n_mariana_islands
            "oman"->MR.strings.oman
            "pakistan"->MR.strings.pakistan
            "palau"->MR.strings.palau
            "palestine"->MR.strings.palestine
            "panama"->MR.strings.panama
            "papua_new_guinea"->MR.strings.papua_new_guinea
            "paraguay"->MR.strings.paraguay
            "peru"->MR.strings.peru
            "philippines"->MR.strings.philippines
            "portugal"->MR.strings.portugal
            "puerto_rico"->MR.strings.puerto_rico
            "qatar"->MR.strings.qatar
            "reunion"->MR.strings.reunion
            "romania"->MR.strings.romania
            "russia"->MR.strings.russia
            "rwanda"->MR.strings.rwanda
            "saint_helena"->MR.strings.saint_helena
            "saint_kitts_nevis"->MR.strings.saint_kitts_nevis
            "saint_lucia"->MR.strings.saint_lucia
            "st_pierre_miquelon"->MR.strings.st_pierre_miquelon
            "saint_vincent_grenadines"->MR.strings.saint_vincent_grenadines
            "samoa"->MR.strings.samoa
            "san_marino"->MR.strings.san_marino
            "sao_tome_principe"->MR.strings.sao_tome_principe
            "saudi_arabia"->MR.strings.saudi_arabia
            "senegal"->MR.strings.senegal
            "serbia"->MR.strings.serbia
            "seychelles"->MR.strings.seychelles
            "sierra_leone"->MR.strings.sierra_leone
            "singapore"->MR.strings.singapore
            "slovakia"->MR.strings.slovakia
            "slovenia"->MR.strings.slovenia
            "solomon_islands"->MR.strings.solomon_islands
            "somalia"->MR.strings.somalia
            "south_africa"->MR.strings.south_africa
            "sri_lanka"->MR.strings.sri_lanka
            "sudan"->MR.strings.sudan
            "suriname"->MR.strings.suriname
            "swaziland"->MR.strings.swaziland
            "switzerland"->MR.strings.switzerland
            "syria"->MR.strings.syria
            "taiwan"->MR.strings.taiwan
            "tajikistan"->MR.strings.tajikistan
            "tanzania"->MR.strings.tanzania
            "thailand"->MR.strings.thailand
            "togo"->MR.strings.togo
            "tonga"->MR.strings.tonga
            "trinidad_tobago"->MR.strings.trinidad_tobago
            "tunisia"->MR.strings.tunisia
            "turkey"->MR.strings.turkey
            "turkmenistan"->MR.strings.turkmenistan
            "turks_caicos_is"->MR.strings.turks_caicos_is
            "tuvalu"->MR.strings.tuvalu
            "uganda"->MR.strings.uganda
            "ukraine"->MR.strings.ukraine
            "united_arab_emirates"->MR.strings.united_arab_emirates
            "uruguay"->MR.strings.uruguay
            "uzbekistan"->MR.strings.uzbekistan
            "vanuatu"->MR.strings.vanuatu
            "venezuela"->MR.strings.venezuela
            "vietnam"->MR.strings.vietnam
            "virgin_islands"->MR.strings.virgin_islands
            "wallis_and_futuna"->MR.strings.wallis_and_futuna
            "west_bank"->MR.strings.west_bank
            "western_sahara"->MR.strings.western_sahara
            "yemen"->MR.strings.yemen
            "zambia"->MR.strings.zambia
            "zimbabwe"->MR.strings.zimbabwe
            "last_online"->MR.strings.last_online
            "member_since"->MR.strings.member_since
            "level"->MR.strings.level
            "bio"->MR.strings.bio
            "favorite_bands"->MR.strings.favorite_bands
            "favorite_artists"->MR.strings.favorite_artists
            "favorite_genres"->MR.strings.favorite_genres
            "contributions"->MR.strings.contributions
            "toggle"->MR.strings.toggle
            "band_name"->MR.strings.band_name
            "country"->MR.strings.country
            "active"->MR.strings.active
            "no_favorite_bands"->MR.strings.no_favorite_bands
            "favorite"->MR.strings.favorite
            "artist_name"->MR.strings.artist_name
            "bands"->MR.strings.bands
            "past"->MR.strings.past
            "no_favorite_artists"->MR.strings.no_favorite_artists
            "genre"->MR.strings.genre
            "no_favorite_genres"->MR.strings.no_favorite_genres
            "user_contributions_table"->MR.strings.user_contributions_table
            "action"->MR.strings.action
            "date"->MR.strings.date
            "table"->MR.strings.table
            "column"->MR.strings.column
            "before"->MR.strings.before
            "after"->MR.strings.after
            "no_contributions"->MR.strings.no_contributions
            "favorite_bands_table"->MR.strings.favorite_bands_table
            "favorite_artists_table"->MR.strings.favorite_artists_table
            "favorite_genres_table"->MR.strings.favorite_genres_table
            "today"->MR.strings.today
            "time_Yp"->MR.strings.time_Yp
            "time_Y"->MR.strings.time_Y
            "time_Mp"->MR.strings.time_Mp
            "time_M"->MR.strings.time_M
            "time_Wp"->MR.strings.time_Wp
            "time_W"->MR.strings.time_W
            "time_Dp"->MR.strings.time_Dp
            "time_D"->MR.strings.time_D
            "time_ago"->MR.strings.time_ago
            "google_error"->MR.strings.google_error
            else->throw IllegalArgumentException("Unknown string resource: $resourceKey")
        }
    }

    fun getStringDesc(key:String):StringDesc{
        return getStringResource(key).desc()
    }
}
