spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Shrendar
    username: root
    password: MjhDQUE3
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8081